### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mongiahammouda**
Fix command option

### CODE REVIEW

**Comment by mprahl** [comment]
@mongiahammouda thanks for the PR! What version of Kustomize are you using?  Locally, I have Kustomize v4.2.0 and the `--enable-alpha-plugins` flag works.

**Comment by mongiahammouda** [comment]
@mprahl Indeed Im using very old version :( that use --enable_alpha_plugins , so probably This PR is useless but I was expecting requirement section that tell us which version to use

**Comment by yiraeChristineKim** [comment]
my version is v4.5.7 so --enable-alpha-plugins work.  I added recommend ver at "installation -> step 7"  https://github.com/open-cluster-management-io/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus. it is good to add recommend ver here. Thanks!

**Comment by dhaiducek** [comment]
@mongiahammouda If you'd like, you can update this PR to add a Kustomize version prerequisite (the `--enable-alpha-plugins` command appeared in `v4.0.1`). Alternatively we could close this PR since, as already noted, that version came out in Feb 2021.

**Comment by dhaiducek** [comment]
@mongiahammouda As there has been no updates, I'm closing this PR per my previous comment. Please reopen this if there are any updates you'd like us to consider.

**Pull request closed without merging**
