### PR TITLE
Make `Placement` the default

### PR DESCRIPTION
**Pull request by dhaiducek**
`PlacementRule` is deprecated

ref: https://issues.redhat.com/browse/ACM-1286

### CODE REVIEW

**Comment by dhaiducek** [comment]
That's more like it 🙂

**Comment by dhaiducek** [comment]
The ManagedClusterSetBinding definitely puts a wrinkle here as far as UX goes, but we'll have to do this eventually...

**Comment by mprahl** [comment]
@dhaiducek , I think this will need a rebase after #136

**Pull request merged**
